version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - "9090:9090"
    command: --config.file=/config/prometheus.yml
    configs:
      - source: prometheus-config
        target: /config/prometheus.yml
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - "node.platform.os == linux"
          - "node.role == manager"
    networks:
      - backend-net
      - signup-net
      - analytics-net

  grafana:
    image: grafana/grafana:6.7.4
    ports:
      - "3000:3000"
    environment:
      GF_USERS_DEFAULT_THEME: light
    configs:
      - source: grafana-datasources
        target: /etc/grafana/provisioning/datasources/datasources.yaml
      - source: grafana-providers
        target: /etc/grafana/provisioning/dashboards/providers.yaml
      - source: signup-dashboard
        target: /var/lib/grafana/dashboards/signup.json
    networks:
      - backend-net
    deploy:
      placement:
        constraints:
          - "node.platform.os == linux"

configs:
  prometheus-config:
    external: true

  grafana-datasources:
    external: true

  grafana-providers:
    external: true

  signup-dashboard:
    external: true

networks:
  backend-net:
    external: true
    name: backend-net

  analytics-net:
    external: true
    name: analytics-net

  signup-net:
    external: true
    name: signup-net