version: "3.7"

services:
  fluentd:
    image: docker4dotnet/fluentd
    environment:
      FLUENTD_CONF: fluentd-signup.conf
    ports:
      - target: 24224
        published: 24224
        protocol: tcp
        mode: host
      - target: 24224
        published: 24224
        protocol: udp
        mode: host
    configs:
      - source: fluentd-signup
        target: /fluentd/etc/fluentd-signup.conf
    networks:
      - analytics-net
    deploy:
      mode: global
      placement:
        constraints:
          - "node.platform.os == linux"

configs:
  fluentd-signup:
    external: true

networks:
  analytics-net:
    external: true
    name: analytics-net