version: "3.8"

services:

  signup-web:
    image: signup-web:04-06
    build:
      dockerfile: docker/04-06-persistent-state/signup-web/Dockerfile
    environment:
      - Metrics:Server:Enabled=true
      - Metrics:Application:Enabled=true