version: '3.7'

services:
  signup-db:
    image: docker4dotnet/sql-server:2017
    environment:
      - sa_password=docker4.net!
    networks:
      - signup-net

  signup-web:
    image: signup-web:02-06
    build:
      context: ../..
      dockerfile: docker/02-06-platform-integration/signup-web/v6/Dockerfile
    environment:
      - Dependencies:IReferenceDataLoader=SignUp.Web.ReferenceData.ApiReferenceDataLoader
      - ReferenceDataApi:Url=http://reference-data-api/api
      - Dependencies:IProspectSaveHandler=SignUp.Web.ProspectSave.AsynchronousProspectSaveHandler
      - MessageQueue:Url=nats://${HOST_IP}:4222
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/app/`)"
    depends_on:
      - reference-data-api
    networks:
      - signup-net

  reference-data-api:
    image: reference-data-api
    build:
      context: ../.. 
      dockerfile: docker/02-05-packaging-dotnet-apps/reference-data-api/Dockerfile
    environment: 
      - Logging:LogLevel:Default=Information
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api/`)"
    networks:
      - signup-net

  homepage:
    image: homepage
    build:
      context: ../..
      dockerfile: docker/03-03-frontend-modernize/homepage/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=PathPrefix(`/`)"
    networks:
      - signup-net

  proxy:
    image: traefik:v2.3-windowsservercore-1809
    command:
      - "--providers.docker"
      - "--providers.docker.endpoint=npipe:////./pipe/docker_engine"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=signup-net"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - "8080:80"
      - "8088:8080"
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine      
    networks:
      - signup-net

  signup-save-handler:
    image: save-handler
    build:
      context: ../.. 
      dockerfile: docker/03-05-backend-async-messaging/save-handler/Dockerfile
    environment: 
      - Logging:LogLevel:Default=Information
      - MessageQueue:Url=nats://${HOST_IP}:4222
    networks:
      - signup-net

networks:
  signup-net: