version: "3.8"

services:

  signup-index-handler:
    image: index-handler
    environment:
      - Metrics:Server:Enabled=true
      - Metrics:Application:Enabled=true
    ports:
      - "8091:80"
    depends_on:
      - elasticsearch
    networks:
      - signup-net

  elasticsearch:
    image: elasticsearch
    networks:
      - signup-net

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - signup-net

networks:
  signup-net:
